sudo: false
language: erlang
otp_release: 19.1
install: true
before_script:
- wget https://s3.amazonaws.com/rebar3/rebar3
- chmod +x rebar3
env: PATH=.:$PATH
cache:
  directories:
  - $HOME/.cache/rebar3/
script: rebar3 compile
